const { makeCanonicalFvgId } = require('./smc');
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const STATE=path.join(__dirname,'entry-zone-state.json');
const HIST=path.join(__dirname,'entry-zone-history.jsonl');
let zones={};try{zones=JSON.parse(fs.readFileSync(STATE,'utf8'))}catch(_){}
const n=v=>Number.isFinite(Number(v))?Number(v):null;
const norm=v=>{if(!v)return null;const p=Date.parse(v);return Number.isFinite(p)?new Date(p).toISOString():String(v)};
const save=()=>fs.writeFileSync(STATE,JSON.stringify(zones,null,2));
const evt=r=>fs.appendFileSync(HIST,JSON.stringify(r)+'\\n');
function stage(a){const s=a?.signalDiagnostics?.signalStage;if(s==='CONFIRMED SETUP')return'CONFIRMED';if(a?.signalDiagnostics?.candidateOnly)return'CANDIDATE';if(a?.entryOpportunityWatch?.active)return'OPPORTUNITY';if(a?.preEntryOpportunityWatch?.active)return'PRE-OPPORTUNITY';return s||'TRACKING'}
function key(symbol,l){const f=norm(l.formationDatetime);return f?[symbol,l.direction||'NA',l.timeframe||'NA',f].join('|'):null}
function existingKey(z){const f=norm(z?.latest?.formationDatetime||z?.formationDatetime);return f?[z.symbol,z.direction||z?.latest?.direction||'NA',z.timeframe||z?.latest?.timeframe||'NA',f].join('|'):null}
function width(l){const lo=n(l.bestZoneLow),hi=n(l.bestZoneHigh);return lo===null||hi===null?null:Math.abs(hi-lo)}
function overlap(a,b,c,d){if([a,b,c,d].some(v=>v===null))return 0;const lo=Math.max(Math.min(a,b),Math.min(c,d)),hi=Math.min(Math.max(a,b),Math.max(c,d)),ov=Math.max(0,hi-lo),sm=Math.max(1e-12,Math.min(Math.abs(b-a),Math.abs(d-c)));return ov/sm}
function fuzzy(z,symbol,l){if(!z||z.symbol!==symbol||z.direction!==l.direction)return false;const lt=z.latest||{},et=lt.timeframe||z.timeframe||'NA',nt=l.timeframe||'NA';if(et!==nt)return false;const el=n(lt.bestZoneLow),eh=n(lt.bestZoneHigh),nl=n(l.bestZoneLow),nh=n(l.bestZoneHigh),eb=n(lt.bestEntryPrice),nb=n(l.bestEntryPrice);const bw=Math.max((el!==null&&eh!==null)?Math.abs(eh-el):0,width(l)||0,1e-8);return overlap(el,eh,nl,nh)>=0.45||(eb!==null&&nb!==null&&Math.abs(eb-nb)<=bw*1.5)}
function find(symbol,l){if(l?.fvgId&&zones[l.fvgId])return zones[l.fvgId];const k=key(symbol,l);if(k){const exact=Object.values(zones).filter(z=>existingKey(z)===k).sort((a,b)=>String(b.lastSeenAt||'').localeCompare(String(a.lastSeenAt||'')));if(exact.length)return exact[0];const legacy=Object.values(zones).filter(z=>!existingKey(z)&&fuzzy(z,symbol,l)).sort((a,b)=>String(b.lastSeenAt||'').localeCompare(String(a.lastSeenAt||'')));return legacy[0]||null}return Object.values(zones).filter(z=>fuzzy(z,symbol,l)).sort((a,b)=>String(b.lastSeenAt||'').localeCompare(String(a.lastSeenAt||'')))[0]||null}
function makeId(symbol,l){if(l?.fvgId)return l.fvgId;const f=norm(l.formationDatetime);const canonicalId=f?makeCanonicalFvgId(symbol,l.direction||'NA',l.timeframe||'NA',f):null;if(canonicalId)return canonicalId;const normalizedSymbol=String(symbol||'').toUpperCase();const direction=String(l.direction||'NA').toUpperCase();const timeframe=String(l.timeframe||'NA').toUpperCase();const seed=[normalizedSymbol,direction,timeframe,new Date().toISOString(),Math.random()].join('|');const h=crypto.createHash('sha1').update(seed).digest('hex').slice(0,10);return `${normalizedSymbol.replace('/','')}-${direction}-${timeframe}-${h}`}
function snap(symbol,id,l,a){return{timestamp:new Date().toISOString(),zoneId:id,fvgId:l.fvgId||null,symbol,direction:l.direction,timeframe:l.timeframe||null,source:l.source||null,formationDatetime:norm(l.formationDatetime),formationIndex:n(l.formationIndex),state:l.state||null,stage:stage(a),score:n(l.score),requiredScore:n(l.requiredScore),contextDirection:l.contextDirection||null,setupDirection:l.setupDirection||null,price:n(l.currentPrice),bestEntryPrice:n(l.bestEntryPrice),bestZoneLow:n(l.bestZoneLow),bestZoneHigh:n(l.bestZoneHigh),lastAcceptablePrice:n(l.lastAcceptablePrice),worstEntryPrice:n(l.worstEntryPrice),distanceToBestAtr:n(l.distanceToBestAtr),zoneStatus:l.zoneStatus||null,reason:l.reason||null}}
function trackEntryZone(symbol,a){const l=a?.entryZoneLifecycle;if(!l?.active||!l.direction)return null;let z=find(symbol,l),id=z?.zoneId||makeId(symbol,l),s=snap(symbol,id,l,a),now=s.timestamp,st=s.stage;if(!z){z=zones[id]={zoneId:id,fvgId:l.fvgId||null,symbol,direction:l.direction,timeframe:l.timeframe||null,source:l.source||null,formationDatetime:s.formationDatetime,formationIndex:s.formationIndex,firstSeenAt:now,lastSeenAt:now,firstSnapshot:s,closestSnapshot:s,firstInZoneAt:l.state==='IN ZONE'?now:null,firstPreOpportunityAt:st==='PRE-OPPORTUNITY'?now:null,firstOpportunityAt:st==='OPPORTUNITY'?now:null,firstCandidateAt:st==='CANDIDATE'?now:null,firstConfirmedAt:st==='CONFIRMED'?now:null,finalState:l.state==='MISSED'?'MISSED BEFORE CONFIRMATION':null,latest:s};evt({event:'ZONE_DISCOVERED',...s})}else{if(!z.formationDatetime&&s.formationDatetime){z.formationDatetime=s.formationDatetime;z.formationIndex=s.formationIndex;evt({event:'STRUCTURAL_IDENTITY_ATTACHED',...s})}z.lastSeenAt=now;z.latest=s;const od=Math.abs(n(z.closestSnapshot?.distanceToBestAtr)??Infinity),nd=Math.abs(n(s.distanceToBestAtr)??Infinity);if(nd<od){z.closestSnapshot=s;evt({event:'CLOSEST_TO_BEST',...s})}const mark=(k,c,e)=>{if(!z[k]&&c){z[k]=now;evt({event:e,...s})}};mark('firstInZoneAt',l.state==='IN ZONE','IN_ZONE');mark('firstPreOpportunityAt',st==='PRE-OPPORTUNITY','PRE_OPPORTUNITY');mark('firstOpportunityAt',st==='OPPORTUNITY','OPPORTUNITY');mark('firstCandidateAt',st==='CANDIDATE','CANDIDATE');if(!z.firstConfirmedAt&&st==='CONFIRMED'){z.firstConfirmedAt=now;z.finalState=l.state==='MISSED'?'CONFIRMED TOO LATE':'CONFIRMED IN TIME';evt({event:'CONFIRMED',...s})}if(l.state==='MISSED'&&!z.finalState){z.finalState=z.firstConfirmedAt?'CONFIRMED TOO LATE':'MISSED BEFORE CONFIRMATION';evt({event:'MISSED',...s})}}save();return z}
function getEntryZones({symbol,limit=100}={}){let a=Object.values(zones);if(symbol)a=a.filter(x=>x.symbol===symbol);return a.sort((x,y)=>String(y.lastSeenAt||'').localeCompare(String(x.lastSeenAt||''))).slice(0,Math.min(Number(limit)||100,500))}
function getEntryZoneHistory({symbol,zoneId,limit=100}={}){if(!fs.existsSync(HIST))return[];let a=fs.readFileSync(HIST,'utf8').split(/\\r?\\n/).filter(Boolean).map(x=>{try{return JSON.parse(x)}catch(_){return null}}).filter(Boolean);if(symbol)a=a.filter(x=>x.symbol===symbol);if(zoneId)a=a.filter(x=>x.zoneId===zoneId);return a.slice(-Math.min(Number(limit)||100,1000)).reverse()}
function clearEntryZoneHistory(){zones={};for(const f of[STATE,HIST])try{fs.unlinkSync(f)}catch(_){}}
module.exports={trackEntryZone,getEntryZones,getEntryZoneHistory,clearEntryZoneHistory};
